import {DurableObject} from "cloudflare:workers";
import {SESSION_TTL_MS,defaultBridgeState,generateSessionCode,mergeBridgeState,normaliseBridgeState,normaliseSessionCode,safeDisplayName,safeSessionName} from "./bridge-session-core.js";

const json=(body,status=200)=>new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store","x-content-type-options":"nosniff"}});
const randomToken=()=>{const bytes=crypto.getRandomValues(new Uint8Array(32));return [...bytes].map(value=>value.toString(16).padStart(2,"0")).join("")};
const sha256=async value=>[...new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value)))].map(value=>value.toString(16).padStart(2,"0")).join("");
const readJson=async(request,max=18000)=>{const text=await request.text();if(text.length>max)throw new Error("PAYLOAD_TOO_LARGE");return text?JSON.parse(text):{}};
const bearer=request=>{const match=request.headers.get("authorization")?.match(/^Bearer ([a-f0-9]{64})$/i);return match?.[1]||""};

export class BridgeSession extends DurableObject{
  constructor(ctx,env){super(ctx,env);this.ctx=ctx;this.env=env;this.session=null;ctx.blockConcurrencyWhile(async()=>{this.session=await ctx.storage.get("session")||null})}
  sockets(role){return this.ctx.getWebSockets(role?role:undefined)}
  clients(){return this.sockets("viewer").map(socket=>{try{const data=socket.deserializeAttachment()||{};return {id:data.id||"unknown",name:data.name||"Bridge Display",joinedAt:data.joinedAt||0}}catch{return {id:"unknown",name:"Bridge Display",joinedAt:0}}})}
  snapshot(){if(!this.session)return null;return {sessionId:this.session.code,sessionName:this.session.name,createdAt:this.session.createdAt,lastActivity:this.session.lastActivity,expiresAt:this.session.lastActivity+SESSION_TTL_MS,ended:!!this.session.ended,connectedClients:this.clients().length,clients:this.clients(),state:normaliseBridgeState(this.session.state)}}
  send(socket,payload){try{socket.send(JSON.stringify(payload));return true}catch{return false}}
  broadcast(payload){for(const socket of this.sockets())this.send(socket,payload)}
  broadcastPresence(){const snapshot=this.snapshot();if(snapshot)this.broadcast({type:"presence",connectedClients:snapshot.connectedClients,clients:snapshot.clients,lastActivity:snapshot.lastActivity})}
  async save(){await this.ctx.storage.put("session",this.session)}
  async authorised(request){if(!this.session)return false;const token=bearer(request);return !!token&&(await sha256(token))===this.session.hostTokenHash}
  async create(request){if(this.session&&!this.session.ended)return json({error:"SESSION_EXISTS"},409);const body=await readJson(request),now=Date.now();if(!body.hostTokenHash||!/^[a-f0-9]{64}$/i.test(body.hostTokenHash))return json({error:"INVALID_HOST_TOKEN"},400);this.session={code:normaliseSessionCode(body.code),name:safeSessionName(body.name),hostTokenHash:body.hostTokenHash,createdAt:now,lastActivity:now,ended:false,state:defaultBridgeState()};if(!this.session.code)return json({error:"INVALID_SESSION_CODE"},400);await this.save();await this.ctx.storage.setAlarm(now+SESSION_TTL_MS);return json(this.snapshot(),201)}
  async update(request){if(!this.session||this.session.ended)return json({error:"SESSION_UNAVAILABLE"},410);if(!await this.authorised(request))return json({error:"HOST_AUTH_REQUIRED"},403);const body=await readJson(request),now=Date.now();this.session.state=mergeBridgeState(this.session.state,body.patch||{},now);this.session.lastActivity=now;await this.save();await this.ctx.storage.setAlarm(now+SESSION_TTL_MS);const snapshot=this.snapshot();this.broadcast({type:"state",state:snapshot.state,session:snapshot});return json(snapshot)}
  async end(request,reason="ended"){if(!this.session)return json({error:"SESSION_UNAVAILABLE"},410);if(reason==="ended"&&!await this.authorised(request))return json({error:"HOST_AUTH_REQUIRED"},403);const code=this.session.code;this.broadcast({type:"session-ended",reason});for(const socket of this.sockets())try{socket.close(4001,"Session ended")}catch{}await this.ctx.storage.deleteAll();this.session=null;return json({ended:true,sessionId:code})}
  async connect(request){if(!this.session||this.session.ended)return json({error:"SESSION_UNAVAILABLE"},410);if(request.headers.get("upgrade")?.toLowerCase()!=="websocket")return json({error:"WEBSOCKET_UPGRADE_REQUIRED"},426);const url=new URL(request.url),preview=url.searchParams.get("preview")==="1",name=safeDisplayName(url.searchParams.get("name")),pair=new WebSocketPair(),[client,server]=Object.values(pair),attachment={role:preview?"preview":"viewer",id:crypto.randomUUID(),name,joinedAt:Date.now()};server.serializeAttachment(attachment);this.ctx.acceptWebSocket(server,[attachment.role]);this.send(server,{type:"welcome",session:this.snapshot(),state:normaliseBridgeState(this.session.state)});if(!preview)this.broadcastPresence();return new Response(null,{status:101,webSocket:client})}
  async fetch(request){if(request.headers.get("x-bridge-internal")!=="1")return json({error:"NOT_FOUND"},404);const path=new URL(request.url).pathname;try{if(path==="/internal/create"&&request.method==="POST")return this.create(request);if(path==="/internal/status"&&request.method==="GET")return this.session&&!this.session.ended?json(this.snapshot()):json({error:"SESSION_UNAVAILABLE"},410);if(path==="/internal/update"&&request.method==="POST")return this.update(request);if(path==="/internal/end"&&request.method==="DELETE")return this.end(request);if(path==="/internal/ws"&&request.method==="GET")return this.connect(request);return json({error:"METHOD_NOT_ALLOWED"},405)}catch(error){return json({error:error?.message==="PAYLOAD_TOO_LARGE"?"PAYLOAD_TOO_LARGE":"INVALID_REQUEST"},error?.message==="PAYLOAD_TOO_LARGE"?413:400)}}
  async webSocketMessage(socket,message){if(typeof message!=="string"||message.length>1024){this.send(socket,{type:"error",error:"INVALID_MESSAGE"});return}let body;try{body=JSON.parse(message)}catch{this.send(socket,{type:"error",error:"INVALID_MESSAGE"});return}if(body.type==="ping"){this.send(socket,{type:"pong",at:Date.now()});return}this.send(socket,{type:"error",error:"READ_ONLY_CLIENT"})}
  async webSocketClose(socket,code,reason){try{socket.close(code,reason)}catch{}this.broadcastPresence()}
  async alarm(){if(this.session&&Date.now()-this.session.lastActivity>=SESSION_TTL_MS)await this.end(new Request("https://internal/expiry"),"expired");else if(this.session)await this.ctx.storage.setAlarm(this.session.lastActivity+SESSION_TTL_MS)}
}

async function bridgeApi(request,env,url){const parts=url.pathname.split("/").filter(Boolean),code=normaliseSessionCode(parts[3]);if(url.pathname==="/api/bridge/sessions"&&request.method==="POST"){let body;try{body=await readJson(request,2000)}catch{return json({error:"INVALID_REQUEST"},400)}for(let attempt=0;attempt<8;attempt++){const sessionCode=generateSessionCode(),hostToken=randomToken(),stub=env.BRIDGE_SESSIONS.getByName(sessionCode),response=await stub.fetch(new Request("https://bridge.internal/internal/create",{method:"POST",headers:{"content-type":"application/json","x-bridge-internal":"1"},body:JSON.stringify({code:sessionCode,name:safeSessionName(body.name),hostTokenHash:await sha256(hostToken)})}));if(response.status===409)continue;if(!response.ok)return response;const session=await response.json();return json({...session,hostToken,joinUrl:`${url.origin}/bridge/?session=${sessionCode}`},201)}return json({error:"SESSION_CODE_UNAVAILABLE"},503)}if(!code)return json({error:"INVALID_SESSION_CODE"},400);const action=parts[4]||"status",stub=env.BRIDGE_SESSIONS.getByName(code),headers=new Headers(request.headers);headers.set("x-bridge-internal","1");if(action==="ws"&&request.method==="GET")return stub.fetch(new Request(`https://bridge.internal/internal/ws${url.search}`,{method:"GET",headers}));if(action==="status"&&request.method==="GET")return stub.fetch(new Request("https://bridge.internal/internal/status",{headers}));if(action==="state"&&request.method==="POST"){const body=await request.text();return stub.fetch(new Request("https://bridge.internal/internal/update",{method:"POST",headers,body}))}if(action==="end"&&request.method==="DELETE")return stub.fetch(new Request("https://bridge.internal/internal/end",{method:"DELETE",headers}));return json({error:"NOT_FOUND"},404)}

export default{async fetch(request,env){const url=new URL(request.url);if(url.pathname.startsWith("/api/bridge/sessions"))return bridgeApi(request,env,url);return env.ASSETS.fetch(request)}};
