import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import {createRequire} from "node:module";
const require=createRequire(import.meta.url),api=require("../public/js/bridge-state.js");
const bridge=await readFile(new URL("../public/bridge/index.html",import.meta.url),"utf8"),gm=await readFile(new URL("../public/gm/index.html",import.meta.url),"utf8"),gmScript=await readFile(new URL("../public/js/gm-hologram.js",import.meta.url),"utf8"),bridgeScript=await readFile(new URL("../public/js/bridge.js",import.meta.url),"utf8"),stateScript=await readFile(new URL("../public/js/bridge-state.js",import.meta.url),"utf8");

assert.doesNotMatch(bridge,/gmPassword|gmUnlock|ACCESS_HASH|GM TRANSMISSION CONTROL|hidden campaign/i,"public bridge must not expose the DM gate or controls");
for(const id of ["bridgeJoin","bridgeJoinForm","bridgeSessionCode","bridgeHologram","hologramText","bridgeAlert","shipMeters","navOrigin","navDestination","bridgeFullscreen","bridgeConnection","bridgeSessionLabel"])assert.match(bridge,new RegExp(`id=["']${id}["']`));
assert.match(gm,/id="gmPasswordGate"/);assert.match(gm,/id="gmUnlockForm"/);assert.match(gm,/CREATE SESSION/i);assert.match(gm,/END SESSION/i);assert.match(gm,/BRIDGE DISPLAY CONTROL/i);assert.match(gm,/SEND TO LIVE SESSION/i);assert.match(gm,/LIVE PREVIEW/i);assert.match(gm,/HIDDEN GM NOTES/i);
for(const label of ["RED ALERT","CUSTOMS SCAN","BOUNTY ALERT","BOARDING ALERT","DISTRESS SIGNAL","SHIP DAMAGE","PLANETARY APPROACH","ENCRYPTED MESSAGE"])assert.match(gm,new RegExp(label,"i"));
assert.match(gmScript,/FAR_REACH_SEND_NPC_TO_LIVE_SESSION/);assert.match(gmScript,/farreach:npc-response/);assert.match(bridgeScript,/requestFullscreen/);assert.match(bridgeScript,/h\.skipToken/);assert.match(bridgeScript,/Date\.now\(\)-\(hologram\.sentAt/);
assert.match(stateScript,/new WebSocket/);assert.match(stateScript,/RECONNECTING/);assert.match(stateScript,/Math\.min\(30000/);assert.match(stateScript,/authorization:`Bearer/);assert.doesNotMatch(stateScript,/localStorage|BroadcastChannel/,"cross-device bridge must not fall back to browser-local sync");
const defaults=api.normalise();assert.equal(defaults.ship.hull,100);assert.equal(defaults.hologram.active,false);assert.equal(defaults.mode,"NORMAL");assert.equal(api.normaliseSessionCode("fr-7k2q"),"FR-7K2Q");assert.equal(api.normaliseSessionCode("FR-OI01"),"");
const safe=api.normalise({mode:"RED ALERT",hologram:{active:true,type:"portrait",name:"<script>Voss",image:"https://evil.test/x.png",text:"<b>Hold</b>",speed:"fast"},ship:{hull:140,shields:-5,heat:50}});assert.equal(safe.mode,"RED ALERT");assert.equal(safe.hologram.image,"");assert.doesNotMatch(safe.hologram.name,/[<>]/);assert.doesNotMatch(safe.hologram.text,/[<>]/);assert.equal(safe.ship.hull,100);assert.equal(safe.ship.shields,0);assert.equal(safe.ship.heat,50);
console.log("Public join flow, full-screen bridge separation, locked GM session controls, reconnect UX and client state validation passed.");
