import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import {pathToFileURL} from "node:url";
import {createHash,randomBytes} from "node:crypto";
import {defaultBridgeState,generateSessionCode,mergeBridgeState,normaliseBridgeState,sanitisePatch,SESSION_TTL_MS} from "../bridge-session-core.js";

const core=defaultBridgeState(),partial=mergeBridgeState({...core,ship:{...core.ship,name:"Nightjar",hull:80}},{ship:{hull:55}});assert.equal(partial.ship.name,"Nightjar");assert.equal(partial.ship.hull,55,"partial updates must preserve unrelated state");const safe=sanitisePatch({mode:"RED ALERT",hiddenNotes:"secret",ship:{hull:150,unknown:"bad"},hologram:{image:"https://evil.test/x",text:"<b>Alert</b>"}});assert.equal(safe.ship.hull,100);assert.equal("unknown" in safe.ship,false);assert.equal("hiddenNotes" in safe,false);assert.equal(safe.hologram.image,"");assert.doesNotMatch(safe.hologram.text,/[<>]/);assert.equal(SESSION_TTL_MS,21600000);for(let i=0;i<40;i++)assert.match(generateSessionCode(values=>values.fill(i)),/^FR-[23456789ABCDEFGHJKLMNPQRSTUVWXYZ]{4}$/);

class Socket{constructor(name){this.attachment={role:"viewer",id:crypto.randomUUID(),name,joinedAt:Date.now()};this.messages=[];this.closed=false}deserializeAttachment(){return this.attachment}send(value){this.messages.push(JSON.parse(value))}close(){this.closed=true}}
class Storage{constructor(){this.map=new Map();this.alarm=null}async get(key){return this.map.get(key)}async put(key,value){this.map.set(key,structuredClone(value))}async setAlarm(value){this.alarm=value}async deleteAll(){this.map.clear()}}
class Context{constructor(storage,sockets=[]){this.storage=storage;this.list=sockets;this.ready=Promise.resolve()}blockConcurrencyWhile(callback){this.ready=Promise.resolve(callback())}getWebSockets(tag){return tag?this.list.filter(socket=>socket.attachment.role===tag):this.list}acceptWebSocket(socket,tags){socket.attachment.role=tags[0];this.list.push(socket)}}
let source=await readFile(new URL("../worker.js",import.meta.url),"utf8");source=source.replace('import {DurableObject} from "cloudflare:workers";','class DurableObject{constructor(ctx,env){this.ctx=ctx;this.env=env}}').replace('from "./bridge-session-core.js"',`from "${pathToFileURL(new URL("../bridge-session-core.js",import.meta.url).pathname).href}"`);const module=await import(`data:text/javascript;base64,${Buffer.from(source).toString("base64")}`),{BridgeSession}=module;
class Namespace{constructor(){this.rooms=new Map()}getByName(name){if(!this.rooms.has(name)){const roomContext=new Context(new Storage()),instance=new BridgeSession(roomContext,{});this.rooms.set(name,{instance,ready:roomContext.ready})}const room=this.rooms.get(name);return {fetch:async request=>{await room.ready;return room.instance.fetch(request)}}}}
const namespace=new Namespace(),workerEnv={BRIDGE_SESSIONS:namespace,ASSETS:{fetch:()=>new Response("asset")}};let apiResponse=await module.default.fetch(new Request("https://farreach.test/api/bridge/sessions",{method:"POST",body:JSON.stringify({name:"API Session"})}),workerEnv),created=await apiResponse.json();assert.equal(apiResponse.status,201);assert.match(created.sessionId,/^FR-/);assert.match(created.hostToken,/^[a-f0-9]{64}$/);assert.match(created.joinUrl,/\/bridge\/\?session=FR-/);apiResponse=await module.default.fetch(new Request(`https://farreach.test/api/bridge/sessions/${created.sessionId}/state`,{method:"POST",body:JSON.stringify({patch:{ship:{hull:1}}})}),workerEnv);assert.equal(apiResponse.status,403);apiResponse=await module.default.fetch(new Request(`https://farreach.test/api/bridge/sessions/${created.sessionId}/state`,{method:"POST",headers:{authorization:`Bearer ${created.hostToken}`},body:JSON.stringify({patch:{ship:{hull:81}}})}),workerEnv);assert.equal(apiResponse.status,200);apiResponse=await module.default.fetch(new Request(`https://farreach.test/api/bridge/sessions/${created.sessionId}/status`),workerEnv);assert.equal((await apiResponse.json()).state.ship.hull,81,"Worker API must route authenticated state to the named session object");
const player1=new Socket("Player One"),player2=new Socket("TV Display"),storage=new Storage(),ctx=new Context(storage,[player1,player2]),room=new BridgeSession(ctx,{});await ctx.ready;const hostToken=randomBytes(32).toString("hex"),hostTokenHash=createHash("sha256").update(hostToken).digest("hex");let response=await room.create(new Request("https://room/internal/create",{method:"POST",body:JSON.stringify({code:"FR-7K2Q",name:"Pale Hound — Session 14",hostTokenHash})}));assert.equal(response.status,201);assert.equal(room.snapshot().connectedClients,2);assert.doesNotMatch(JSON.stringify(room.snapshot()),new RegExp(hostToken),"public session snapshots must not expose the host token");assert.equal("hostTokenHash" in room.snapshot(),false);
const patch={mode:"RED ALERT",hologram:{active:true,name:"VANTA PRIME PORT CONTROL",text:"Pale Hound, hold position at Beacon Seven.",speed:"normal",nonce:7},alert:{active:true,title:"RED ALERT",severity:"CRITICAL"},ship:{hull:72,shields:45,location:"Beacon Seven"}};response=await room.update(new Request("https://room/internal/update",{method:"POST",headers:{authorization:`Bearer ${hostToken}`},body:JSON.stringify({patch})}));assert.equal(response.status,200);for(const player of [player1,player2]){const stateMessage=player.messages.find(message=>message.type==="state");assert.ok(stateMessage,`${player.attachment.name} did not receive broadcast`);assert.equal(stateMessage.state.hologram.text,patch.hologram.text);assert.equal(stateMessage.state.mode,"RED ALERT");assert.equal(stateMessage.state.ship.hull,72)}
const newPlayer=new Socket("Late Joiner");ctx.list.push(newPlayer);room.send(newPlayer,{type:"welcome",session:room.snapshot(),state:normaliseBridgeState(room.session.state)});assert.equal(newPlayer.messages[0].state.alert.title,"RED ALERT");assert.equal(newPlayer.messages[0].state.hologram.active,true,"new player must receive active state immediately");
const refreshedCtx=new Context(storage,[player1,player2,newPlayer]),refreshed=new BridgeSession(refreshedCtx,{});await refreshedCtx.ready;assert.equal(refreshed.snapshot().state.ship.location,"Beacon Seven","refresh/reconnect must restore stored state");response=await refreshed.update(new Request("https://room/internal/update",{method:"POST",headers:{authorization:`Bearer ${randomBytes(32).toString("hex")}`},body:JSON.stringify({patch:{ship:{hull:1}}})}));assert.equal(response.status,403,"non-host mutation must be rejected");const before=refreshed.snapshot().state.ship.hull;await refreshed.webSocketMessage(player1,JSON.stringify({type:"state",patch:{ship:{hull:1}}}));assert.equal(refreshed.snapshot().state.ship.hull,before);assert.equal(player1.messages.at(-1).error,"READ_ONLY_CLIENT");response=await refreshed.end(new Request("https://room/internal/end",{method:"DELETE",headers:{authorization:`Bearer ${hostToken}`}}));assert.equal(response.status,200);assert.ok([player1,player2,newPlayer].every(player=>player.closed));assert.ok(player2.messages.some(message=>message.type==="session-ended"));
console.log("Durable session creation, two-player broadcast, late join, stored reconnect, read-only security and session ending passed.");
